spring:
  application:
    name: mcp-client-demo


ai:
  openai:
    api-key: ${OPENAI_API_KEY}
  mcp:
    client-id:
      enable: true
      stdio:
        server-configuration: 'classpath:mcp-server.json'